language: cpp
jobs:
  include:
  - os: linux
    dist: bionic
    env: BUILD_TYPE=Linux
  - os: linux
    dist: bionic
    env: BUILD_TYPE=Libretro
  - os: osx
    env: BUILD_TYPE=iOS
  - os: osx
    env: BUILD_TYPE=macOS

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$BUILD_TYPE" == "Linux" ]]; then sudo apt-get install -y build-essential libsdl2-dev libglew-dev; fi
  - if [[ "$BUILD_TYPE" == "macOS" ]]; then brew install sdl2; fi

script:
  - if [[ "$BUILD_TYPE" == "iOS" ]]; then xcodebuild clean build -sdk iphonesimulator -project platforms/ios/Gearboy.xcodeproj -scheme Gearboy CODE_SIGNING_REQUIRED=NO; fi
  - if [[ "$BUILD_TYPE" == "Linux" ]]; then cd platforms/linux && make; fi
  - if [[ "$BUILD_TYPE" == "Libretro" ]]; then cd platforms/libretro && make; fi
  - if [[ "$BUILD_TYPE" == "macOS" ]]; then cd platforms/macos && make; fi
