matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      language: cpp
      env: BUILD_TYPE=linux
    - os: linux
      dist: bionic
      sudo: required
      language: cpp
      env: BUILD_TYPE=libretro
    - os: osx
      language: cpp
      env: BUILD_TYPE=ios
    - os: osx
      language: cpp
      env: BUILD_TYPE=macosx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$BUILD_TYPE" == "linux" ]]; then sudo apt-get install -y build-essential libsdl2-dev; fi
  - if [[ "$BUILD_TYPE" == "macosx" ]]; then brew install sdl2; fi

script:
  - if [[ "$BUILD_TYPE" == "ios" ]]; then xcodebuild clean build -sdk iphonesimulator -project platforms/ios/Gearboy.xcodeproj -scheme Gearboy CODE_SIGNING_REQUIRED=NO; fi
  - if [[ "$BUILD_TYPE" == "linux" ]]; then cd platforms/linux/Gearboy && make; fi
  - if [[ "$BUILD_TYPE" == "libretro" ]]; then cd platforms/libretro && make; fi
  - if [[ "$BUILD_TYPE" == "macosx" ]]; then cd platforms/linux/Gearboy && make; fi
